# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

jQuery(document).ready ($) ->
  jssor_1_SlideshowTransitions = [
    {
      $Duration: 1200
      x: -0.3
      $During: $Left: [
        0.3
        0.7
      ]
      $Easing:
        $Left: $Jease$.$InCubic
        $Opacity: $Jease$.$Lianear
      $Opacity: 2
    }
    {
      $Duration: 1200
      x: 0.3
      $SlideOut: true
      $Easing:
        $Left: $Jease$.$InCubic
        $Opacity: $Jease$.$Linear
      $Opacity: 2
    }
  ]
  jssor_1_options =
    $AutoPlay: true
    $SlideshowOptions:
      $Class: $JssorSlideshowRunner$
      $Transitions: jssor_1_SlideshowTransitions
      $TransitionsOrder: 1
    $ArrowNavigatorOptions: $Class: $JssorArrowNavigator$
    $BulletNavigatorOptions: $Class: $JssorBulletNavigator$
    $ThumbnailNavigatorOptions:
      $Class: $JssorThumbnailNavigator$
      $Cols: 1
      $Align: 0
  jssor_1_slider = new $JssorSlider$('jssor_1', jssor_1_options)
  #responsive code begin
  #you can remove responsive code if you don't want the slider scales while window resizes

  ScaleSlider = ->
    refSize = jssor_1_slider.$Elmt.parentNode.clientWidth
    if refSize
      refSize = Math.min(refSize, 900)
      jssor_1_slider.$ScaleWidth refSize
    else
      window.setTimeout ScaleSlider, 30
    return

  ScaleSlider()
  $(window).bind 'load', ScaleSlider
  $(window).bind 'resize', ScaleSlider
  $(window).bind 'orientationchange', ScaleSlider
  #responsive code end
  return

# ---
# generated by js2coffee 2.1.0
